name: PR TESTS

on:
  pull_request:
    branches: [main]

jobs:
  lib-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: |
          bun install --frozen-lockfile
          cd libs/koala-nest && bun install --frozen-lockfile

      - name: Run lib unit tests
        run: bun run test

  lib-e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: koala_nest
          PGDATA: /data/postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: |
          bun install --frozen-lockfile
          cd libs/koala-nest && bun install --frozen-lockfile

      - name: Run lib e2e tests
        run: bun run test:e2e
        env:
          DATABASE_URL: postgresql://postgres:root@localhost:5432/koala_nest
          NODE_ENV: test

  cli-e2e-tests:
    name: CLI E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: |
          bun install --frozen-lockfile
          cd libs/koala-nest && bun install --frozen-lockfile

      - name: Run CLI e2e tests
        run: bun run test:cli:e2e
        env:
          CI: '1'

  docs-tests:
    name: Docs Site Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install root dependencies
        run: bun install --frozen-lockfile

      - name: Install docs site dependencies
        run: cd libs/doc/site && bun install --frozen-lockfile

      - name: Generate docs manifest
        run: bun run doc:manifest

      - name: Run unit tests
        run: cd libs/doc/site && bun run test:unit

      - name: Install Playwright Chromium
        run: cd libs/doc/site && bunx playwright install --with-deps chromium

      - name: Run e2e tests
        run: cd libs/doc/site && bun run e2e
